package com.alyndroid.thirdeyechecklist.util

import com.alyndroid.thirdeyechecklist.data.model.CountryModel

interface SharedPref{
    companion object {
        val app_version = "app_version"
        val gard_number = "gard_number"
        val min_needed_items = "min_needed_items"
    }
}

interface ExtrasKeys{
    companion object {
        val startFrom = "where_the_app_start_from"
        val gard_number = "gard_number"
        val min_needed_items = "min_needed_items"
    }
}

interface Extras{
    companion object {
        val from_app_launcher = "1"
        val from_scratch_shortcut = "2"
        val gard_number = "gard_number"
        val min_needed_items = "min_needed_items"
    }
}

interface ErrorMsg{
    companion object {
        val no_connection = 1
        val internal_server = 2
    }
}

interface Constant{
    companion object {
        val countries = listOf<CountryModel>(
            CountryModel("1", "AW", "آروبا", "Aruba"),
            CountryModel("2", "AZ", "أذربيجان", "Azerbaijan"),
            CountryModel("3", "AM", "أرمينيا", "Armenia"),
            CountryModel("4", "ES", "أسبانيا", "Spain"),
            CountryModel("5", "AU", "أستراليا", "Australia"),
            CountryModel("6", "AF", "أفغانستان", "Afghanistan"),
            CountryModel("7", "AL", "ألبانيا", "Albania"),
            CountryModel("8", "DE", "ألمانيا", "Germany"),
            CountryModel("9", "AG", "أنتيجوا وبربودا", "Antigua and Barbuda"),
            CountryModel("10", "AO", "أنجولا", "Angola"),
            CountryModel("11", "AI", "أنجويلا", "Anguilla"),
            CountryModel("12", "AD", "أندورا", "Andorra"),
            CountryModel("13", "UY", "أورجواي", "Uruguay"),
            CountryModel("14", "UZ", "أوزبكستان", "Uzbekistan"),
            CountryModel("15", "UG", "أوغندا", "Uganda"),
            CountryModel("16", "UA", "أوكرانيا", "Ukraine"),
            CountryModel("17", "IE", "أيرلندا", "Ireland"),
            CountryModel("18", "IS", "أيسلندا", "Iceland"),
            CountryModel("19", "ET", "اثيوبيا", "Ethiopia"),
            CountryModel("20", "ER", "اريتريا", "Eritrea"),
            CountryModel("21", "EE", "استونيا", "Estonia"),
            CountryModel("22", "IL", "اسرائيل", "Israel"),
            CountryModel("23", "AR", "الأرجنتين", "Argentina"),
            CountryModel("24", "JO", "الأردن", "Jordan"),
            CountryModel("25", "EC", "الاكوادور", "Ecuador"),
            CountryModel("26", "AE", "الامارات العربية المتحدة", "United Arab Emirates"),
            CountryModel("27", "BS", "الباهاما", "Bahamas"),
            CountryModel("28", "BH", "البحرين", "Bahrain"),
            CountryModel("29", "BR", "البرازيل", "Brazil"),
            CountryModel("30", "PT", "البرتغال", "Portugal"),
            CountryModel("31", "BA", "البوسنة والهرسك", "Bosnia and Herzegovina"),
            CountryModel("32", "GA", "الجابون", "Gabon"),
            CountryModel("33", "ME", "الجبل الأسود", "Montenegro"),
            CountryModel("34", "DZ", "الجزائر", "Algeria"),
            CountryModel("35", "DK", "الدانمرك", "Denmark"),
            CountryModel("36", "CV", "الرأس الأخضر", "Cape Verde"),
            CountryModel("37", "SV", "السلفادور", "El Salvador"),
            CountryModel("38", "SN", "السنغال", "Senegal"),
            CountryModel("39", "SD", "السودان", "Sudan"),
            CountryModel("40", "SE", "السويد", "Sweden"),
            CountryModel("41", "EH", "الصحراء الغربية", "Western Sahara"),
            CountryModel("42", "SO", "الصومال", "Somalia"),
            CountryModel("43", "CN", "الصين", "China"),
            CountryModel("44", "IQ", "العراق", "Iraq"),
            CountryModel("45", "VA", "الفاتيكان", "Vatican City"),
            CountryModel("46", "PH", "الفيلبين", "Philippines"),
            CountryModel("47", "AQ", "القطب الجنوبي", "Antarctica"),
            CountryModel("48", "CM", "الكاميرون", "Cameroon"),
            CountryModel("49", "CG", "الكونغو - برازافيل", "Congo (Republic)"),
            CountryModel("50", "KW", "الكويت", "Kuwait"),
            CountryModel("51", "HU", "المجر", "Hungary"),
            CountryModel("52", "IO", "المحيط الهندي البريطاني", "British Indian Ocean Territory"),
            CountryModel("53", "MA", "المغرب", "Morocco"),
            CountryModel("54", "TF", "المقاطعات الجنوبية الفرنسية", "French Southern Territories"),
            CountryModel("55", "MX", "المكسيك", "Mexico"),
            CountryModel("56", "SA", "المملكة العربية السعودية", "Saudi Arabia"),
            CountryModel("57", "GB", "المملكة المتحدة", "United Kingdom"),
            CountryModel("58", "NO", "النرويج", "Norway"),
            CountryModel("59", "AT", "النمسا", "Austria"),
            CountryModel("60", "NE", "النيجر", "Niger"),
            CountryModel("61", "IN", "الهند", "India"),
            CountryModel("62", "US", "الولايات المتحدة الأمريكية", "United States"),
            CountryModel("63", "JP", "اليابان", "Japan"),
            CountryModel("64", "YE", "اليمن", "Yemen"),
            CountryModel("65", "GR", "اليونان", "Greece"),
            CountryModel("66", "code", "اندونيسيا", ""),
            CountryModel("67", "IR", "ايران", "Iran"),
            CountryModel("68", "IT", "ايطاليا", "Italy"),
            CountryModel("69", "PG", "بابوا غينيا الجديدة", "Papua New Guinea"),
            CountryModel("70", "PY", "باراجواي", "Paraguay"),
            CountryModel("71", "PK", "باكستان", "Pakistan"),
            CountryModel("72", "PW", "بالاو", "Palau"),
            CountryModel("73", "BW", "بتسوانا", "Botswana"),
            CountryModel("74", "PN", "بتكايرن", "Pitcairn Islands"),
            CountryModel("75", "BB", "بربادوس", "Barbados"),
            CountryModel("76", "BM", "برمودا", "Bermuda"),
            CountryModel("77", "BN", "بروناي", "Brunei"),
            CountryModel("78", "BE", "بلجيكا", "Belgium"),
            CountryModel("79", "BG", "بلغاريا", "Bulgaria"),
            CountryModel("80", "BZ", "بليز", "Belize"),
            CountryModel("81", "BD", "بنجلاديش", "Bangladesh"),
            CountryModel("82", "PA", "بنما", "Panama"),
            CountryModel("83", "BJ", "بنين", "Benin"),
            CountryModel("84", "BT", "بوتان", "Bhutan"),
            CountryModel("85", "PR", "بورتوريكو", "Puerto Rico"),
            CountryModel("86", "BF", "بوركينا فاسو", "Burkina Faso"),
            CountryModel("87", "BI", "بوروندي", "Burundi"),
            CountryModel("88", "PL", "بولندا", "Poland"),
            CountryModel("89", "BO", "بوليفيا", "Bolivia"),
            CountryModel("90", "PF", "بولينيزيا الفرنسية", "French Polynesia"),
            CountryModel("91", "PE", "بيرو", "Peru"),
            CountryModel("92", "TZ", "تانزانيا", "Tanzania"),
            CountryModel("93", "TH", "تايلند", "Thailand"),
            CountryModel("94", "TW", "تايوان", "Taiwan"),
            CountryModel("95", "TM", "تركمانستان", "Turkmenistan"),
            CountryModel("96", "TR", "تركيا", "Turkey"),
            CountryModel("97", "TT", "ترينيداد وتوباغو", "Trinidad and Tobago"),
            CountryModel("98", "TD", "تشاد", "Chad"),
            CountryModel("99", "TG", "توجو", "Togo"),
            CountryModel("100", "TV", "توفالو", "Tuvalu"),
            CountryModel("101", "TK", "توكيلو", "Tokelau"),
            CountryModel("102", "TO", "تونجا", "Tonga"),
            CountryModel("103", "TN", "تونس", "Tunisia"),
            CountryModel("104", "TL", "تيمور الشرقية", "Timor-Leste"),
            CountryModel("105", "JM", "جامايكا", "Jamaica"),
            CountryModel("106", "GI", "جبل طارق", "Gibraltar"),
            CountryModel("107", "GD", "جرينادا", "Grenada"),
            CountryModel("108", "GL", "جرينلاند", "Greenland"),
            CountryModel("109", "AX", "جزر أولان", "Åland Islands"),
            CountryModel("110", "AN", "جزر الأنتيل الهولندية", ""),
            CountryModel("111", "TC", "جزر الترك وجايكوس", "Turks and Caicos Islands"),
            CountryModel("112", "KM", "جزر القمر", "Comoros"),
            CountryModel("113", "KY", "جزر الكايمن", "Cayman Islands"),
            CountryModel("114", "MH", "جزر المارشال", "Marshall Islands"),
            CountryModel("115", "MV", "جزر الملديف", "Maldives"),
            CountryModel("116", "UM", "جزر الولايات المتحدة البعيدة ا", "U.S. Outlying Islands"),
            CountryModel("117", "SB", "جزر سليمان", "Solomon Islands"),
            CountryModel("118", "FO", "جزر فارو", "Faroe Islands"),
            CountryModel("119", "VI", "جزر فرجين الأمريكية", "U.S. Virgin Islands"),
            CountryModel("120", "VG", "جزر فرجين البريطانية", "British Virgin Islands"),
            CountryModel("121", "FK", "جزر فوكلاند", "Falkland Islands"),
            CountryModel("122", "CK", "جزر كوك", "Cook Islands"),
            CountryModel("123", "CC", "جزر كوكوس", "Cocos (Keeling) Islands"),
            CountryModel("124", "MP", "جزر ماريانا الشمالية", "Northern Mariana Islands"),
            CountryModel("125", "WF", "جزر والس وفوتونا", "Wallis and Futuna"),
            CountryModel("126", "CX", "جزيرة الكريسماس", "Christmas Island"),
            CountryModel("127", "BV", "جزيرة بوفيه", "Bouvet Island"),
            CountryModel("128", "IM", "جزيرة مان", "Isle of Man"),
            CountryModel("129", "NF", "جزيرة نورفوك", "Norfolk Island"),
            CountryModel("130", "HM", "جزيرة هيرد وماكدونالد", "Heard & McDonald Islands"),
            CountryModel("131", "CF", "جمهورية افريقيا الوسطى", "Central African Republic"),
            CountryModel("132", "CZ", "جمهورية التشيك", "Czech Republic"),
            CountryModel("133", "DO", "جمهورية الدومينيك", "Dominican Republic"),
            CountryModel("134", "CD", "جمهورية الكونغو الديمقراطية", "Congo (DRC)"),
            CountryModel("135", "ZA", "جمهورية جنوب افريقيا", "South Africa"),
            CountryModel("136", "GT", "جواتيمالا", "Guatemala"),
            CountryModel("137", "GP", "جوادلوب", "Guadeloupe"),
            CountryModel("138", "GU", "جوام", "Guam"),
            CountryModel("139", "GE", "جورجيا", "Georgia"),
            CountryModel("140", "GS", "جورجيا الجنوبية وجزر ساندويتش ", "South Georgia & South Sandwich"),
            CountryModel("141", "DJ", "جيبوتي", "Djibouti"),
            CountryModel("142", "JE", "جيرسي", "Jersey"),
            CountryModel("143", "DM", "دومينيكا", "Dominica"),
            CountryModel("144", "RW", "رواندا", "Rwanda"),
            CountryModel("145", "RU", "روسيا", "Russia"),
            CountryModel("146", "BY", "روسيا البيضاء", "Belarus"),
            CountryModel("147", "RO", "رومانيا", "Romania"),
            CountryModel("148", "RE", "روينيون", "Réunion"),
            CountryModel("149", "ZM", "زامبيا", "Zambia"),
            CountryModel("150", "ZW", "زيمبابوي", "Zimbabwe"),
            CountryModel("151", "CI", "ساحل العاج", "Côte d’Ivoire"),
            CountryModel("152", "WS", "ساموا", "Samoa"),
            CountryModel("153", "AS", "ساموا الأمريكية", "American Samoa"),
            CountryModel("154", "SM", "سان مارينو", "San Marino"),
            CountryModel("155", "PM", "سانت بيير وميكولون", "Saint Pierre and Miquelon"),
            CountryModel("156", "VC", "سانت فنسنت وغرنادين", "St. Vincent & Grenadines"),
            CountryModel("157", "KN", "سانت كيتس ونيفيس", "Saint Kitts and Nevis"),
            CountryModel("158", "LC", "سانت لوسيا", "Saint Lucia"),
            CountryModel("159", "MF", "سانت مارتين", "Saint Martin"),
            CountryModel("160", "SH", "سانت هيلنا", "Saint Helena"),
            CountryModel("161", "ST", "ساو تومي وبرينسيبي", "São Tomé and Príncipe"),
            CountryModel("162", "LK", "سريلانكا", "Sri Lanka"),
            CountryModel("163", "SJ", "سفالبارد وجان مايان", "Svalbard and Jan Mayen"),
            CountryModel("164", "SK", "سلوفاكيا", "Slovakia"),
            CountryModel("165", "SI", "سلوفينيا", "Slovenia"),
            CountryModel("166", "SG", "سنغافورة", "Singapore"),
            CountryModel("167", "SZ", "سوازيلاند", "Swaziland"),
            CountryModel("168", "SY", "سوريا", "Syria"),
            CountryModel("169", "SR", "سورينام", "Suriname"),
            CountryModel("170", "CH", "سويسرا", "Switzerland"),
            CountryModel("171", "SL", "سيراليون", "Sierra Leone"),
            CountryModel("172", "SC", "سيشل", "Seychelles"),
            CountryModel("173", "CL", "شيلي", "Chile"),
            CountryModel("174", "RS", "صربيا", "Serbia"),
            CountryModel("175", "CS", "صربيا والجبل الأسود", ""),
            CountryModel("176", "TJ", "طاجكستان", "Tajikistan"),
            CountryModel("177", "OM", "عمان", "Oman"),
            CountryModel("178", "GM", "غامبيا", "Gambia"),
            CountryModel("179", "GH", "غانا", "Ghana"),
            CountryModel("180", "GF", "غويانا", "French Guiana"),
            CountryModel("181", "GY", "غيانا", "Guyana"),
            CountryModel("182", "GN", "غينيا", "Guinea"),
            CountryModel("183", "GQ", "غينيا الاستوائية", "Equatorial Guinea"),
            CountryModel("184", "GW", "غينيا بيساو", "Guinea-Bissau"),
            CountryModel("185", "VU", "فانواتو", "Vanuatu"),
            CountryModel("186", "FR", "فرنسا", "France"),
            CountryModel("187", "PS", "فلسطين", "Palestine"),
            CountryModel("188", "VE", "فنزويلا", "Venezuela"),
            CountryModel("189", "FI", "فنلندا", "Finland"),
            CountryModel("190", "VN", "فيتنام", "Vietnam"),
            CountryModel("191", "FJ", "فيجي", "Fiji"),
            CountryModel("192", "CY", "قبرص", "Cyprus"),
            CountryModel("193", "KG", "قرغيزستان", "Kyrgyzstan"),
            CountryModel("194", "QA", "قطر", "Qatar"),
            CountryModel("195", "KZ", "كازاخستان", "Kazakhstan"),
            CountryModel("196", "NC", "كاليدونيا الجديدة", "New Caledonia"),
            CountryModel("197", "HR", "كرواتيا", "Croatia"),
            CountryModel("198", "KH", "كمبوديا", "Cambodia"),
            CountryModel("199", "CA", "كندا", "Canada"),
            CountryModel("200", "CU", "كوبا", "Cuba"),
            CountryModel("201", "KR", "كوريا الجنوبية", "South Korea"),
            CountryModel("202", "KP", "كوريا الشمالية", "North Korea"),
            CountryModel("203", "CR", "كوستاريكا", "Costa Rica"),
            CountryModel("204", "CO", "كولومبيا", "Colombia"),
            CountryModel("205", "KI", "كيريباتي", "Kiribati"),
            CountryModel("206", "KE", "كينيا", "Kenya"),
            CountryModel("207", "LV", "لاتفيا", "Latvia"),
            CountryModel("208", "LA", "لاوس", "Laos"),
            CountryModel("209", "LB", "لبنان", "Lebanon"),
            CountryModel("210", "LU", "لوكسمبورج", "Luxembourg"),
            CountryModel("211", "LY", "ليبيا", "Libya"),
            CountryModel("212", "LR", "ليبيريا", "Liberia"),
            CountryModel("213", "LT", "ليتوانيا", "Lithuania"),
            CountryModel("214", "LI", "ليختنشتاين", "Liechtenstein"),
            CountryModel("215", "LS", "ليسوتو", "Lesotho"),
            CountryModel("216", "MQ", "مارتينيك", "Martinique"),
            CountryModel("217", "MO", "ماكاو الصينية", "Macau"),
            CountryModel("218", "MT", "مالطا", "Malta"),
            CountryModel("219", "ML", "مالي", "Mali"),
            CountryModel("220", "MY", "ماليزيا", "Malaysia"),
            CountryModel("221", "YT", "مايوت", "Mayotte"),
            CountryModel("222", "MG", "مدغشقر", "Madagascar"),
            CountryModel("223", "EG", "مصر", "Egypt"),
            CountryModel("224", "MK", "مقدونيا", "Macedonia (FYROM)"),
            CountryModel("225", "MW", "ملاوي", "Malawi"),
            CountryModel("227", "MN", "منغوليا", "Mongolia"),
            CountryModel("228", "MR", "موريتانيا", "Mauritania"),
            CountryModel("229", "MU", "موريشيوس", "Mauritius"),
            CountryModel("230", "MZ", "موزمبيق", "Mozambique"),
            CountryModel("231", "MD", "مولدافيا", "Moldova"),
            CountryModel("232", "MC", "موناكو", "Monaco"),
            CountryModel("233", "MS", "مونتسرات", "Montserrat"),
            CountryModel("234", "MM", "ميانمار", "Myanmar (Burma)"),
            CountryModel("235", "FM", "ميكرونيزيا", "Micronesia"),
            CountryModel("236", "NA", "ناميبيا", "Namibia"),
            CountryModel("237", "NR", "نورو", "Nauru"),
            CountryModel("238", "NP", "نيبال", "Nepal"),
            CountryModel("239", "NG", "نيجيريا", "Nigeria"),
            CountryModel("240", "NI", "نيكاراجوا", "Nicaragua"),
            CountryModel("241", "NZ", "نيوزيلاندا", "New Zealand"),
            CountryModel("242", "NU", "نيوي", "Niue"),
            CountryModel("243", "HT", "هايتي", "Haiti"),
            CountryModel("244", "HN", "هندوراس", "Honduras"),
            CountryModel("245", "NL", "هولندا", "Netherlands"),
            CountryModel("246", "HK", "هونج كونج الصينية", "Hong Kong")
        )
    }
}

